### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by sediq-khan** [paulpv/audio-loopback#1]
Hi,

We have an application written in Electron Js, which does not really access low-level functionalities. We would like to use your software to pick internal system audio and use it. I was wondering if your application is open source? or if we can use it for Windows and Mac. We would like to have it bundled with our application and install it as a pre-requisite using our installer. What do you think?

Thank you,
Sediq

**Comment by paulpv** [comment]
Wow! Super unimpressed with both myself and GitHub notifications that I had never seen this message!

Of course you or anyone can use this app.
I will add a MIT license.

So sorry for the delay.

Closing to hopefully get your attention.
